### ISSUE TITLE
Did the speaker encoder trained before the VC model?

### ISSUE THREAD

**Issue by Lukelluke** [MingjieChen/LowResourceVC#2]
Nice job, @MingjieChen ,

and i'm so interested in ur arxiv paper , i will read it later.

1. I wanna figure out how u train the speaker encoder in the process, did it pretrained before we train the VC model? Or u choose to train together at the same time?

2. I noticed that u described in ur paper that the embedding is 126 dims, and u still wanna use the CIN model?  in the original CIN paper in image field, it pointed out that the `related embedding` use `[1, feature_classes]x[feature_classes, feature_dim]`, and in that way we calculate the \gamma & \beta, so as to make current embedding have more relationship between all speakers. See more from the [relates issues about CIN in image_field](https://github.com/MingtaoGuo/Conditional-Instance-Norm-for-n-Style-Transfer/issues/1) 
 Maybe my thought is wrong, i wanna know how the embedding that not in the form of one-hot that can use CIN patern, and use \gamma & \beta to calculate the related embedding?

3. And would u please write the preparation processes of data preparing? I wanna have it a try~~~

All the best,
Luke Huang

**Comment by MingjieChen** [comment]
Hello,

I trained the speaker encoder together with the GAN model.

In this project, I did not used CIN, I am trying to normalize the model weights. Sorry, I do not understand your second question.

**Comment by MingjieChen** [comment]
For preprocessing script, please see preprocess_vctk.py and run_pre.sh
