### ISSUE TITLE
Style encoder contrastive loss and gradient penalty

### ISSUE THREAD

**Issue by ywh-my** [MingjieChen/LowResourceVC#4]
Firstly , I found that you have  been implemented the code of style encoder contrastive loss , why do not you use it ? 
Secondly , I found that the gradient penalty can make convergence faster , why do not you use it ?
I wish you can answer me . Thank you very much.

**Comment by MingjieChen** [comment]
Hello,

I just tried contrastive loss but found it not perfect compatible with the adversarial training losses, so I didn't go further with it. I found there is a small performance degradation when using the gradient penalty, but I am not very sure. It's just my own subjective perspective.
